"""add_payment_gateways

Revision ID: 0002
Revises: 0001
Create Date: 2025-08-18 08:11:49.159090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_gateway_type = sa.Enum(
        "TELEGRAM_STARS",
        "YOOKASSA",
        "YOOMONEY",
        "CRYPTOMUS",
        "HELEKET",
        name="paymentgatewaytype",
    )

    currency = sa.Enum(
        "USD",
        "XTR",
        "RUB",
        name="currency",
    )

    op.create_table(
        "payment_gateways",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", payment_gateway_type, nullable=False),
        sa.Column("currency", currency, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("shop_id", sa.String(), nullable=True),
        sa.Column("api_token", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )

    op.bulk_insert(
        sa.table(
            "payment_gateways",
            sa.column("type", payment_gateway_type),
            sa.column("currency", currency),
            sa.column("is_active", sa.Boolean),
            sa.column("shop_id", sa.String),
            sa.column("api_token", sa.String),
        ),
        [
            {
                "type": "TELEGRAM_STARS",
                "currency": "XTR",
                "is_active": True,
                "shop_id": None,
                "api_token": None,
            },
            {
                "type": "YOOKASSA",
                "currency": "RUB",
                "is_active": False,
                "shop_id": None,
                "api_token": None,
            },
            {
                "type": "YOOMONEY",
                "currency": "RUB",
                "is_active": False,
                "shop_id": None,
                "api_token": None,
            },
            {
                "type": "CRYPTOMUS",
                "currency": "USD",
                "is_active": False,
                "shop_id": None,
                "api_token": None,
            },
            {
                "type": "HELEKET",
                "currency": "USD",
                "is_active": False,
                "shop_id": None,
                "api_token": None,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_gateways")
    # ### end Alembic commands ###
