"""Estimand SDK package."""

from .assignment import (
    AssignmentResult,
    assign,
    choose_variation,
    fnv1a32,
    get_bucket_ranges,
    hash_value,
)
from .client import (
    ConfigCacheMissError,
    EstimandClient,
    EstimandClientConfig,
    EstimandSDKConfigError,
    EstimandSDKError,
    EstimandSDKHTTPError,
    EstimandSDKRequestError,
)
from .evaluator import (
    REASON_FEATURE_DISABLED,
    REASON_FEATURE_NOT_FOUND,
    REASON_FEATURE_UNPUBLISHED,
    REASON_NO_MATCHING_RULE,
    REASON_NO_VARIANTS,
    REASON_OUTSIDE_COVERAGE,
    REASON_RULE_DEFAULT_MATCHED,
    REASON_RULE_MATCHED,
    REASON_VARIANT_FORCED,
    EvaluationResult,
    evaluate_feature,
    evaluate_feature_from_payload,
    evaluate_features,
)
from .evaluator import (
    evaluate_features as evaluate_features_from_payload,
)
from .models import (
    ConfigPayload,
    EventBatchResponse,
    EventPayload,
    FeatureConfig,
    RuleConfig,
    VariationConfig,
)

__all__ = [
    "AssignmentResult",
    "EstimandClient",
    "EstimandClientConfig",
    "EstimandSDKError",
    "EstimandSDKConfigError",
    "EstimandSDKHTTPError",
    "EstimandSDKRequestError",
    "ConfigCacheMissError",
    "EvaluationResult",
    "REASON_FEATURE_DISABLED",
    "REASON_FEATURE_NOT_FOUND",
    "REASON_FEATURE_UNPUBLISHED",
    "REASON_NO_MATCHING_RULE",
    "REASON_NO_VARIANTS",
    "REASON_OUTSIDE_COVERAGE",
    "REASON_RULE_DEFAULT_MATCHED",
    "REASON_RULE_MATCHED",
    "REASON_VARIANT_FORCED",
    "ConfigPayload",
    "FeatureConfig",
    "RuleConfig",
    "VariationConfig",
    "evaluate_feature",
    "evaluate_features",
    "evaluate_feature_from_payload",
    "evaluate_features_from_payload",
    "assign",
    "choose_variation",
    "fnv1a32",
    "get_bucket_ranges",
    "hash_value",
    "EventPayload",
    "EventBatchResponse",
    "EvaluationResult",
]
